version: "3.0"

services:
  is_stateful:
    image: registry.docker.tests:5000/softwareag/is_stateful:10.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_TYPE: docker
        CC_TEMPLATE: is_stateful
        CC_TEMPLATE_ENV: is
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
    ports:
      - "5555:5555"
      - "9999:9999"

  is_stateful_managed:
    image: registry.docker.tests:5000/softwareag/is_stateful_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
      args:
        ENV_TYPE: docker
        CC_TEMPLATE: is_stateful
        CC_TEMPLATE_ENV: is
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce

  cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-server
    ports:
      - "8090:8090"
      - "8091:8091"