version: "3"

networks:
  sagdevops:

services:

  setup_provisioning:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops
    command: echo "Setting up the provisoning with Command Central. Please check the progress of each setup on each of the runing setup instances"
    depends_on:
      - is1
      - is2
      - tcserver

########################## CCE setup ################################
  cce:
    image: store/softwareag/commandcentral:${TAG}-server
    hostname: cce
    networks:
      - sagdevops
    ports:
      - "8090:8090"
      - "8091:8091"

  setup_cce:
    image: softwareag/commandcentral:$TAG-client
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=sag-repos
      - CC_TEMPLATE_ENV=sag-repos
      - ENV_TYPE=server
      - CC_SAG_REPO_USR
      - CC_SAG_REPO_PWD
    networks:
      - sagdevops
    volumes:
      - ./:/src
    command: bash -c "sagccant apply_licenses && sagccant setup"
    depends_on:
      - cce

########################## IS setup ################################

  is1:
    image: ${REGISTRY}softwareag/is_stateful_managed:${TAG}
    hostname: is1
    networks:
      - sagdevops
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    ports:
      - "5555:5555"
    depends_on:
      - is_db
      - tcserver

  is2:
    image: ${REGISTRY}softwareag/is_stateful_managed:${TAG}
    hostname: is2
    networks:
      - sagdevops
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    ports:
      - "5556:5555"
    depends_on:
      - is_db
      - tcserver

  is_db:
    image: ${REGISTRY}softwareag_dbs/is-oracle:${TAG}
    networks:
      - sagdevops
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## TC setup ################################

  tcserver:
    image: ${REGISTRY}softwareag/tcserver_managed:${TAG}
    networks:
      - sagdevops
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    expose:
      - "9510"
      - "9530"
      - "9540"
    ports:
      - "9510:9510"
    environment:
      - TC_HOST=tcserver
      - TC_STORAGE=1g
      - TC_OFFHEAP=1g