version: "3"

networks:
  sagdevops:

services:
  cce:
    image: store/softwareag/commandcentral:${TAG}-server
    hostname: cce
    networks:
      - sagdevops
    ports:
      - "8090:8090"
      - "8091:8091"

  setup_cce:
    image: softwareag/commandcentral:$TAG-client
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=sag-repos
      - CC_TEMPLATE_ENV=sag-repos
      - ENV_TYPE=server
      - CC_SAG_REPO_USR
      - CC_SAG_REPO_PWD
    networks:
      - sagdevops
    volumes:
      - ./:/src
    command: bash -c "sagccant apply_licenses && sagccant setup"
    depends_on:
      - cce

  is1:
    image: store/softwareag/commandcentral:${TAG}-node
    hostname: is1
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    ports:
      - "5555:5555"
    depends_on:
      - umserver

  setup_is1:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=is-layer/tpl_is_stateless_messaging.yaml
      - CC_TEMPLATE_ENV=is
      - CC_TEMPLATE_ENV_TARGET_HOST=is1
      - CC_TEMPLATE_ENV_TYPE=server
      - CC_SPM_HOST=is1
      - CC_SPM_PORT=8092
    volumes:
      - ./:/src
    command: sagccant setup
    depends_on:
      - is1
      - cce

  umserver:
    image: store/softwareag/commandcentral:${TAG}-node
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    ports:
      - "9000:9000"

  setup_um:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=um-layer
      - CC_TEMPLATE_ENV=um
      - CC_TEMPLATE_ENV_TARGET_HOST=umserver
      - CC_TEMPLATE_ENV_TYPE=server
      - CC_SPM_HOST=umserver
      - CC_SPM_PORT=8092
    volumes:
      - ./:/src
    command: sagccant setup
    depends_on:
      - umserver
      - cce

  umserver2:
    image: ${REGISTRY}softwareag/umserver_managed:${TAG}
    networks:
      - sagdevops
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    ports:
      - "9000:9000"