version: "3.0"

services:
  custombuilder:
    image: softwareag/custombuilder:$TAG
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        PARENT_IMAGE: store/softwareag/commandcentral:${TAG}-builder

  cce-client:
    image: softwareag/commandcentral:$TAG-client
    build:
      context: .
      dockerfile: Dockerfile.cce.client
      args:
        PARENT_BUILDER: store/softwareag/commandcentral:${TAG}-builder
        PARENT_IMAGE: centos:7