version: "3"

networks:
  sagdevops:

services:
########################## IS setup ################################

  is1:
    image: ${REGISTRY}softwareag/is_stateful:${TAG}
    hostname: is1
    networks:
      - sagdevops
    ports:
      - "5555:5555"
    depends_on:
      - is_db
      - tcserver

  is2:
    image: ${REGISTRY}softwareag/is_stateful:${TAG}
    hostname: is2
    networks:
      - sagdevops
    ports:
      - "5556:5555"
    depends_on:
      - is_db
      - tcserver

  is_db:
    image: ${REGISTRY}softwareag_dbs/is-oracle:${TAG}
    networks:
      - sagdevops
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## TC setup ################################

  tcserver:
    image: ${REGISTRY}softwareag/tcserver:${TAG}
    networks:
      - sagdevops
    expose:
      - "9510"
      - "9530"
      - "9540"
    ports:
      - "9510:9510"
    environment:
      - TC_HOST=tcserver
      - TC_STORAGE=1g
      - TC_OFFHEAP=1g