version: "3"

networks:
  sagdevops_bpms:
    external: true

services:

########################## CCE setup ################################
  cce:
    #image: softwareag/commandcentral/custom/mymirror:10.1.0.1-server
    image: registry.docker.tests:5000/softwareag/commandcentral/custom/empower:10.1-server
    hostname: cce
    networks:
      - sagdevops_bpms
    ports:
      - "8090:8090"
      - "8091:8091"

  setup_cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    environment:
      - CC_CLIENT=docker
    volumes:
      - ./:/src
    networks:
      - sagdevops_bpms
    command: sagccant licenses
    depends_on:
      - cce

########################## IS setup ################################

  is:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: is
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - is_db
      - um
      - tc

  setup_is:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=is-layer
      - CC_BASE_ENV=is
      - CC_SPM_HOST=is
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - is
      - cce

  is_db:
    image: registry.docker.tests:5000/softwareag_dbs/is-oracle:10.1
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## MWS setup ################################

  mws:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: mws
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8585"
      - "8586"
      - "8092"
      - "8093"
    ports:
      - "8585:8585"
    depends_on:
      - mws_db

  setup_mws:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=mws-layer
      - CC_BASE_ENV=mws
      - CC_SPM_HOST=mws
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - mws
      - cce

  mws_db:
    image: registry.docker.tests:5000/softwareag_dbs/mws-oracle:10.1
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## BPMS setup ################################

  bpms:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: bpms
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - bpms_db
      - um
      - tc

  setup_bpms:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=bpms-layer
      - CC_BASE_ENV=bpms
      - CC_SPM_HOST=bpms
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - bpms
      - cce

  bpms_db:
    image: registry.docker.tests:5000/softwareag_dbs/bpms-oracle:10.1
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## IS / UM setup directly from docker ################################

  um:
    image: registry.docker.tests:5000/softwareag/umserver:10.1
    hostname: um
    networks:
      - sagdevops_bpms
    volumes:
      - ./licenses/lnxamd64/UniversalMessaging.xml:/opt/softwareag/UniversalMessaging/server/umserver/licence.xml
    expose:
      - "8092"
      - "8093"
      - "9000"
    ports:
      - "9000:9000"

  tc:
    image: registry.docker.tests:5000/softwareag/tcserver:10.1
    hostname: tc
    networks:
      - sagdevops_bpms
    volumes:
      - ./licenses/lnxamd64/terracotta-license.key:/opt/softwareag/Terracotta/terracotta-license.key
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"