version: "3"

networks:
  sagdevops:

services:

########################## CCE setup ################################
  cce:
    #image: softwareag/commandcentral/custom/mymirror:10.1.0.1-server
    image: registry.docker.tests:5000/softwareag/commandcentral/custom/empower:10.1-server
    hostname: cce
    networks:
      - sagdevops
    ports:
      - "8090:8090"
      - "8091:8091"

  setup_cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    environment:
      - CC_CLIENT=docker
    volumes:
      - ./:/src
    networks:
      - sagdevops
    command: sagccant licenses
    depends_on:
      - cce

########################## IS setup ################################

  is:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: is
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"

  setup_is:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=is-layer
      - CC_BASE_ENV=is
      - CC_SPM_HOST=is
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - setup_is_db
      - is
      - cce

  is_db:
    image: registry.docker.tests:5000/softwareag/base-oracle-xe-11g
    networks:
      - sagdevops
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

  setup_is_db:
    image: registry.docker.tests:5000/softwareag/dbcreator
    networks:
      - sagdevops
    environment:
      - db.name=webm
      - db.type=oracle
      - db.host=is_db
      - db.port=1521
      - db.tablespace.dir=/u01/app/oracle/oradata/XE
      - db.admin.username=system
      - db.admin.password=oracle
      - db.username=is_dbuser
      - db.password=strong123!
      - db.product.version=latest
      - db.component.version=latest
      - db.components=[STR]
      - db.products=[IS]
    depends_on:
      - is_db

########################## MWS setup ################################

  mws:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: mws
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8585"
      - "8586"
      - "8092"
      - "8093"
    ports:
      - "8585:8585"

  setup_mws:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=mws-layer
      - CC_BASE_ENV=mws
      - CC_SPM_HOST=mws
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - setup_mws_db
      - mws
      - cce

  mws_db:
    image: registry.docker.tests:5000/softwareag/base-oracle-xe-11g
    networks:
      sagdevops:
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

  setup_mws_db:
    image: registry.docker.tests:5000/softwareag/dbcreator
    networks:
      - sagdevops
    environment:
      - db.name=webm
      - db.type=oracle
      - db.host=mws_db
      - db.port=1521
      - db.tablespace.dir=/u01/app/oracle/oradata/XE
      - db.admin.username=system
      - db.admin.password=oracle
      - db.username=mws_dbuser
      - db.password=strong123!
      - db.product.version=latest
      - db.component.version=latest
      - db.components=[STR]
      - db.products=[MWS]
    depends_on:
      - mws_db

########################## BPMS setup ################################

  bpms:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: bpms
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"

  setup_bpms:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=bpms-layer
      - CC_BASE_ENV=bpms
      - CC_SPM_HOST=bpms
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - setup_bpms_db
      - bpms
      - cce

  bpms_db:
    image: registry.docker.tests:5000/softwareag/base-oracle-xe-11g
    networks:
      sagdevops:
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

  setup_bpms_db:
    image: registry.docker.tests:5000/softwareag/dbcreator
    networks:
      - sagdevops
    environment:
      - db.name=webm
      - db.type=oracle
      - db.host=bpms_db
      - db.port=1521
      - db.tablespace.dir=/u01/app/oracle/oradata/XE
      - db.admin.username=system
      - db.admin.password=oracle
      - db.username=bpms_dbuser
      - db.password=strong123!
      - db.product.version=latest
      - db.component.version=latest
      - db.components=[STR]
      - db.products=[IS,BPM,MWS]
    depends_on:
      - bpms_db

########################## UM setup ################################

  um:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: um
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "9000"
    ports:
      - "9000:9000"

  setup_um:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=um-layer
      - CC_BASE_ENV=um
      - CC_SPM_HOST=um
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - um
      - cce

########################## TC setup ################################

  tc:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-node
    hostname: tc
    networks:
      - sagdevops
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "9010"
      - "9020"
      - "9030"
      - "9040"

  setup_tc:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-client
    volumes:
      - ./:/src
    networks:
      - sagdevops
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=tc-layer
      - CC_BASE_ENV=tc
      - CC_SPM_HOST=tc
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - tc
      - cce