version: "3.0"

services:
  umserver:
    image: registry.docker.tests:5000/softwareag/umserver:10.1
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9000"
    ports:
      - "9000:9000"

  umserver_managed:
    image: registry.docker.tests:5000/softwareag/umserver_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
    expose:
      - "9000"
    ports:
      - "9001:9000"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce
    
  cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-server
    ports:
      - "8090:8090"
      - "8091:8091"
