version: "3.0"

services:
  mws_simple_builder:
    image: ${BUILDER_REGISTRY}softwareag/mws_simple_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        CC_TEMPLATE: mws-layer/tpl_mws_simple.yaml
        CC_TEMPLATE_ENV: mws
        CC_TEMPLATE_ENV_TYPE: docker
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
        CC_SAG_REPO_USR: $CC_SAG_REPO_USR
        CC_SAG_REPO_PWD: $CC_SAG_REPO_PWD

  mws_simple:
    image: ${REGISTRY}softwareag/mws_simple:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/mws_simple_builder:${TAG}
        PARENT_IMAGE: centos:7
    expose:
      - "5555"
      - "9999"
    depends_on:
      - mws_simple_builder

  mws_simple_managed:
    image: ${REGISTRY}softwareag/mws_simple_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/mws_simple_builder:${TAG}
        PARENT_IMAGE: ${REGISTRY}softwareag/mws_simple:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - mws_simple_builder
      - mws_simple

  mws_bpms_builder:
    image: ${BUILDER_REGISTRY}softwareag/mws_bpms_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        ENV_TYPE: docker
        CC_TEMPLATE: mws-layer/tpl_mws_bpms.yaml
        CC_TEMPLATE_ENV: mws
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092

  mws_bpms:
    image: ${REGISTRY}softwareag/mws_bpms:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/mws_bpms_builder:${TAG}
        PARENT_IMAGE: centos:7
    expose:
      - "5555"
      - "9999"
    depends_on:
      - mws_bpms_builder

  mws_bpms_managed:
    image: ${REGISTRY}softwareag/mws_bpms_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/mws_bpms_builder:${TAG}
        PARENT_IMAGE: ${REGISTRY}softwareag/mws_bpms:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - mws_bpms_builder
      - mws_bpms