version: "3"

networks:
  sagdevops_bpms:
    external: true

services:

########################## CCE setup ################################
  cce:
    image: store/softwareag/commandcentral:${TAG}-server
    hostname: cce
    networks:
      - sagdevops_bpms
    ports:
      - "9090:8090"
      - "9091:8091"

  setup_cce:
    image: softwareag/commandcentral:$TAG-client
    environment:
      - CC_CLIENT=docker
    networks:
      - sagdevops_bpms
    command: sagccant licenses
    depends_on:
      - cce

########################## IS setup ################################

  is:
    image: store/softwareag/commandcentral:${TAG}-node
    hostname: is
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - is_db
      - umserver
      - tcserver

  setup_is:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=is-layer
      - CC_BASE_ENV=is
      - CC_SPM_HOST=is
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - is
      - cce

  is_db:
    image: ${REGISTRY}softwareag_dbs/is-oracle:${TAG}
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## MWS setup ################################

  mws:
    image: store/softwareag/commandcentral:${TAG}-node
    hostname: mws
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8585"
      - "8586"
      - "8092"
      - "8093"
    ports:
      - "8585:8585"
    depends_on:
      - mws_db

  setup_mws:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=mws-layer
      - CC_BASE_ENV=mws
      - CC_SPM_HOST=mws
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - mws
      - cce

  mws_db:
    image: ${REGISTRY}softwareag_dbs/mws-oracle:${TAG}
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## BPMS setup ################################

  bpms:
    image: store/softwareag/commandcentral:${TAG}-node
    hostname: bpms
    networks:
      - sagdevops_bpms
    environment:
      - CC_AUTO_REGISTER=0
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - bpms_db
      - umserver
      - tcserver

  setup_bpms:
    image: softwareag/commandcentral:$TAG-client
    networks:
      - sagdevops_bpms
    environment:
      - CC_CLIENT=docker
      - CC_TEMPLATE=bpms-layer
      - CC_BASE_ENV=bpms
      - CC_SPM_HOST=bpms
      - CC_SPM_PORT=8092
    command: sagccant setup
    depends_on:
      - bpms
      - cce

  bpms_db:
    image: ${REGISTRY}softwareag_dbs/bpms-oracle:${TAG}
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## IS / UM setup directly from docker ################################

  umserver:
    image: ${REGISTRY}softwareag/umserver:${TAG}
    hostname: um
    networks:
      - sagdevops_bpms
    expose:
      - "8092"
      - "8093"
      - "9000"
    ports:
      - "9000:9000"

  tcserver:
    image: ${REGISTRY}softwareag/tcserver:${TAG}
    hostname: tc
    networks:
      - sagdevops_bpms
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"