version: "3.0"

services:

  msc_builder:
    image: ${BUILDER_REGISTRY}softwareag/msc_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        CC_TEMPLATE: msc-layer
        CC_TEMPLATE_ENV: msc
        CC_TEMPLATE_ENV_TYPE: docker
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
        CC_SAG_REPO_USR: $CC_SAG_REPO_USR
        CC_SAG_REPO_PWD: $CC_SAG_REPO_PWD

  msc:
    image: ${REGISTRY}softwareag/msc:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/msc_builder:${TAG}
        PARENT_IMAGE: centos:7
    expose:
      - "5555"
      - "9999"
    depends_on:
      - msc_builder

  msc_managed:
    image: ${REGISTRY}softwareag/msc_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/msc_builder:${TAG}
        PARENT_IMAGE: ${REGISTRY}softwareag/msc:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - msc_builder
      - msc