version: "3.0"

services:
  is_stateless_messaging_builder:
    image: ${BUILDER_REGISTRY}softwareag/is_stateless_messaging_builder:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        CC_TEMPLATE: is-layer/tpl_is_stateless_messaging.yaml
        CC_TEMPLATE_ENV: is
        CC_TEMPLATE_ENV_TYPE: docker
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
        CC_SAG_REPO_USR: $CC_SAG_REPO_USR
        CC_SAG_REPO_PWD: $CC_SAG_REPO_PWD

  is_stateless_messaging:
    image: ${REGISTRY}softwareag/is_stateless_messaging:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.unmanaged
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/is_stateless_messaging_builder:${TAG}
        PARENT_IMAGE: centos:7
    expose:
      - "5555"
      - "9999"
    depends_on:
      - is_stateless_messaging_builder

  is_stateless_messaging_managed:
    image: ${REGISTRY}softwareag/is_stateless_managed:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        PARENT_BUILDER: ${BUILDER_REGISTRY}softwareag/is_stateless_messaging_builder:${TAG}
        PARENT_IMAGE: ${REGISTRY}softwareag/is_stateless_messaging:${TAG}
    expose:
      - "5555"
      - "9999"
      - "8092"
      - "8093"
    depends_on:
      - is_stateless_messaging_builder
      - is_stateless_messaging