version: "3"

networks:
  sagdevops:
    external: true

services:
  wmis:
    build:
      context: is_stateful
      dockerfile: Dockerfile
    image: registry.docker.tests:5000/softwareag/wmis_stateful:10.1
    hostname: wmis
    networks:
      - sagdevops
    volumes:
      - ./licenses/lnxamd64/Integration_Server.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml
      - ./licenses/lnxamd64/terracotta-license.key:/opt/softwareag/common/conf/terracotta-license.key
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - um
      - tc

  um:
    image: registry.docker.tests:5000/softwareag/umserver:10.1
    hostname: um
    networks:
      - sagdevops
    volumes:
      - ./licenses/lnxamd64/UniversalMessaging.xml:/opt/softwareag/UniversalMessaging/server/umserver/licence.xml
    expose:
      - "8092"
      - "8093"
      - "9000"
    ports:
      - "9000:9000"

  tc:
    image: registry.docker.tests:5000/softwareag/tcserver:10.1
    hostname: tc
    networks:
      - sagdevops
    volumes:
      - ./licenses/lnxamd64/terracotta-license.key:/opt/softwareag/Terracotta/terracotta-license.key
    expose:
      - "9010"
      - "9020"
      - "9030"
      - "9040"