version: "3.0"

services:
  is:
    image: registry.docker.tests:5000/softwareag/is:10.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
      - "9999:9999"

  is_managed:
    image: registry.docker.tests:5000/softwareag/is_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
    ports:
      - "5555:5555"
      - "9999:9999"
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce

  cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-server
    ports:
      - "8090:8090"
      - "8091:8091"