version: "3"

networks:
  sagdevops_bpms:
    external: true

services:
########################## IS setup ################################
  is1:
    image: registry.docker.tests:5000/softwareag/is_stateful:10.1
    hostname: is1
    networks:
      - sagdevops_bpms
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5555:5555"
    depends_on:
      - is_db
      - tcserver

  is2:
    image: registry.docker.tests:5000/softwareag/is_stateful:10.1
    hostname: is2
    networks:
      - sagdevops_bpms
    expose:
      - "8092"
      - "8093"
      - "5555"
      - "9999"
      - "8094"
    ports:
      - "5556:5555"
    depends_on:
      - is_db
      - tcserver

  is_db:
    image: registry.docker.tests:5000/softwareag_dbs/is-oracle:10.1
    networks:
      - sagdevops_bpms
    expose:
      - "22"
      - "1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

########################## TC setup ################################

  tcserver:
    image: registry.docker.tests:5000/softwareag/tcserver:10.1
    networks:
      - sagdevops_bpms
    environment:
      - TC_HOST=tcserver
      - TC_STORAGE=1g
      - TC_OFFHEAP=1g
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"