version: "3.0"

services:
  tcserver:
    image: registry.docker.tests:5000/softwareag/tcserver:10.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_TYPE: docker
        CC_TEMPLATE: tc-layer
        CC_TEMPLATE_ENV: tc
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"

  tcserver_managed:
    image: registry.docker.tests:5000/softwareag/tcserver_managed:10.1
    build:
      context: .
      dockerfile: Dockerfile.managed
      args:
        ENV_TYPE: docker
        CC_TEMPLATE: tc-layer
        CC_TEMPLATE_ENV: tc
        CC_SPM_HOST: localhost
        CC_SPM_PORT: 8092
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    ports:
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce

  cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-server
    ports:
      - "8090:8090"
      - "8091:8091"