version: "3.0"

services:
  tcserver:
    image: softwareag/tcserver:10.1
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"

  tcserver_managed:
    image: softwareag/tcserver_managed:10.1
    build:
      context: .    
      dockerfile: Dockerfile.managed
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    ports:
      - "8092:8092"
      - "8093:8093"
    environment:
      - CC_SERVER=cce
      - CC_AUTO_REGISTER=1
    depends_on:
      - cce

  cce:
    image: registry.docker.tests:5000/ccdevops/commandcentral:10.1-server
    ports:
      - "8090:8090"
      - "8091:8091"